### ISSUE TITLE
Change BTreeMap to ordermap?

### ISSUE THREAD

**Issue by smmalis37** [smmalis37/ZBot#15]
Would allow full control of the ordering of commands listed in !help, instead of only alphabetical. Worth it?

**Comment by pcioni** [comment]
No? Order is superfluous information with the commands. The only thing we care about is constant access to them.

**Comment by smmalis37** [comment]
Not quite. Like I said we do iterate through all commands for !help. Using ordermap would allow us control over the ordering there. Currently with BTreeMap the ordering is alphabetical, or a HashMap would be random.

**Comment by smmalis37** [comment]
No longer relevant.
