### ISSUE TITLE
Suggestions for architectural improvements

### ISSUE THREAD

**Issue by willmtemple** [smmalis37/ZBot#16]
I think you should build out a simple CLI-like interface and a plugin architecture to dynamically add subcommands. This way, we could add modules easily.

The way it would work would be to have a CLI that could be invoked using a discord message e.g. `@Z help`, `@Z elevator set-track http://youtube.com/some-video-id`, `@Z color ...`. Then make the normal bang-commands like `!help` and friends be aliases to these commands.

Then have a plugin registry in the main file where we can register a function in another module to handle a base command, and route events to individual modules when they occur. This way we could have something like the elevator contained entirely in a separate module, and we could add more modules for maximum memes.

**Comment by smmalis37** [comment]
While not a bad idea, I feel this is overly restrictive on how we would force commands to work. Let's stick with the current approach for now and we can refactor later if we need to.

**Comment by smmalis37** [comment]
This is somewhat handled by using serenity's fancy framework system.
