### ISSUE TITLE
Code organization and sanity

### ISSUE THREAD

**Issue by willmtemple** [smmalis37/ZBot#6]
If this repository is going to become a group meme, we should think about cleaning it up a little bit.

Everything to do with elevator should probably get its own module.

**Comment by pcioni** [comment]
You converted the entire project to PEP8 and spaces instead of tabs, and YOU call this a meme? Honestly.

**Comment by willmtemple** [comment]
@pcioni I didn't make the whole thing spaces. Python suggests using spaces. Here's why: if you use tabs, then there's no easy way to tell when a line is going to overflow your terminal, unless everyone agrees to use the same tabstop, and then why not use spaces? PEP8 specifies line lengths < 80 columns. If you use tabs at 8 spaces, and I use them at 2 spaces, then there's a big difference between how long a line that's indented 4 times is going to be.
